### PR TITLE
Content below Sky Nav animates again

### LINKED ISSUE #1984: The Sky Nav should animate open/closed at smaller viewports
Regression?

Left: https://cloudfour-patterns.netlify.app/iframe.html?args=&id=components-sky-nav--dark&viewMode=story
Right: https://c4dev.wpengine.com

Notice on the left how the content below the nav also animates down/up.

Notice on the right how the content snaps down/up instead.

sky-nav

### PR DESCRIPTION
**Pull request by gerardo-rodriguez**
## Overview

This PR fixes a bug where the content below the Sky Nav menu was not animating open/closed.

Changes include:
- transition the `document.body` instead of all of the wrapper containers
- update demo with more up-to-date header markup

## Screenshots

better

## Testing

The best test method will be using your local Cloud Four WordPress site via `npm link`.

### Checkout both repos

1. Checkout out the `cloudfour.com-wp` `main` branch locally
2. Checkout this `cloudfour.com-patterns` branch locally

### In the `cloudfour.com-patterns` repo

1. `npm ci && npm run build && npm link`

### In the `cloudfour.com-wp` repo

1. In the theme directory: `npm ci && npm link @cloudfour/patterns && npm run build` 

### Confirm

-  [ ] At smaller viewports, the content below the Sky Nav should animate open/closed (try various pages)

## Undo `npm link`

1. In the WP repo: `npm uninstall --no-save @cloudfour/patterns && npm i`
2. In the Patterns repo (delete global symlink): `npm uninstall`

---

- Closes #1984

### CODE REVIEW

**Review by calebeby — APPROVED** [review]

File: src/components/sky-nav/sky-nav.ts [hunk 1]
```diff
@@ -74,34 +65,25 @@ export const initSkyNav = (navButton: HTMLButtonElement) => {
...
+      document.body.style.transform = `translateY(${-heightDiff}px)`;
 
       timeoutId = setTimeout(() => {
         menu.hidden = true;
-        for (const el of elementsToShift) {
-          el.style.transition = '';
-          el.style.transform = '';
-        }
+        document.body.style.transition = '';
+        document.body.style.transform = '';
```
Comment (tylersticka) [inline src/components/sky-nav/sky-nav.ts:74]: I realize this wasn't introduced in this PR, but is there any reason we're not using `style.setProperty` and `style.removeProperty`?

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/removeProperty

**Review by tylersticka — COMMENTED** [review]
Has someone tested this in all of our optimized browsers? I remember on the last version of the site we had to move away from animating `document.body`, but I can't remember if it was IE or some mobile browser that had issues with it.

File: src/components/sky-nav/sky-nav.ts (hunk 1 above)
Comment (calebeby) [reply src/components/sky-nav/sky-nav.ts:74]: I might have put it in there in the first place but I have no preference between the two syntaxes.

Comment (gerardo-rodriguez) [reply src/components/sky-nav/sky-nav.ts]: Updated: https://github.com/cloudfour/cloudfour.com-patterns/pull/1986/commits/84232b630079da353aaf078db86ee2da454c07ed

**Comment by gerardo-rodriguez** [comment]
> Has someone tested this in all of our optimized browsers? I remember on the last version of the site we had to move away from animating `document.body`, but I can't remember if it was IE or some mobile browser that had issues with it.

@tylersticka I was able to confirm it works in the following browsers:
- macOS Firefox
- macOS Chrome
- macOS Edge
- macOS Safari
- ios Safari via Simulator

**Review by tylersticka — APPROVED** [review]
I have not followed all of the described testing steps, but if this has been thoroughly tested and approved by two developers that's good enough for me. If it's misbehaving on production we'll spot it before launch (🤞)
